export const IMAGES_API = '/api/images';
export const STYLES = [
  'contemporary',
  'modern',
  'asian',
  'craftsman',
  'farmhouse',
  'industrial',
  'mediterranean',
  'midcentury',
  'rustic',
  'scandinavian',
  'shabby-chic-style',
  'victorian',
];
export const CATEGORIES = [
  'exterior',
  'living-room',
  'kitchen',
  'dining-room',
  'pendant-lighting',
  'armchairs-and-accent-chairs',
];
export const DISPLAY_NAME = {
  contemporary: 'Contemporary',
  modern: 'Modern',
  asian: 'Asian',
  craftsman: 'Craftsman',
  farmhouse: 'Farmhouse',
  industrial: 'Industrial',
  mediterranean: 'Mediterranean',
  midcentury: 'Midcentury',
  rustic: 'Rustic',
  scandinavian: 'Scandinavian',
  'shabby-chic-style': 'Shabby Chic',
  victorian: 'Victorian',
  exterior: 'Exterior',
  'living-room': 'Living Room',
  kitchen: 'Kitchen',
  'dining-room': 'Dining Room',
  'pendant-lighting': 'Pendant Lighting',
  'armchairs-and-accent-chairs': 'Armchairs and Accent Chairs',
};