export const IMAGES_API = '/api/images';
export const STYLES = [
  'asian',
  'contemporary',
  'craftsman',
  'farmhouse',
  'industrial',
  'mediterranean',
  'midcentury',
  'modern',
  'rustic',
  'scandinavian',
  'shabby-chic-style',
  'victorian',
];
export const CATEGORIES = [
  'exterior',
  'living-room',
  'kitchen',
  'dining-room',
  'pendant-lighting',
  'armchairs-and-accent-chairs',
];
export const DISPLAY_NAME = {
  contemporary: 'Contemporary',
  modern: 'Modern',
  asian: 'Asian',
  craftsman: 'Craftsman',
  farmhouse: 'Farmhouse',
  industrial: 'Industrial',
  mediterranean: 'Mediterranean',
  midcentury: 'Midcentury',
  rustic: 'Rustic',
  scandinavian: 'Scandinavian',
  'shabby-chic-style': 'Shabby Chic',
  victorian: 'Victorian',
  exterior: 'Exterior',
  'living-room': 'Living Room',
  kitchen: 'Kitchen',
  'dining-room': 'Dining Room',
  'pendant-lighting': 'Pendant Lighting',
  'armchairs-and-accent-chairs': 'Armchairs and Accent Chairs',
  other: 'Other',
};
export const PAGE_SUMMARY = {
  contemporary: 'Clean, sleek lines, marked by solid colors with an emphasis on basic shapes and forms',
  modern: 'Neutral color palette, polished surfaces, strong geometric shapes and asymmetry',
  asian: 'Natural fiber elements, bamboo and colors taken from nature to create a serene, calm environment',
  craftsman: '',
  farmhouse: '',
  industrial: '',
  mediterranean: 'Heavy and burnished hardware. Velvets, linens and textured fabrics mix with textured walls',
  midcentury: '',
  rustic: '',
  scandinavian: '',
  'shabby-chic-style': 'Cottage-inspired look with painted motifs, floral prints in muted colors, and vintage accessories',
  victorian: '',
  exterior: '',
  'living-room': '',
  kitchen: '',
  'dining-room': '',
  'pendant-lighting': 'A central aspect of interior design, lights can be simple in structure, yet diverse in design',
  'armchairs-and-accent-chairs': 'An arena for designers to compete, chairs are the ultimate challenge of form-meets-function',
};